In [1]:
1+1

2

In [2]:
## numpy
import numpy as np

In [4]:
lst = [1,2,3,4]
arr=np.array(lst)
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr1.shape

(2, 3)

In [10]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr1.dtype

dtype('int64')

In [16]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.arange(1,10,2).shape

(5,)

In [20]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [23]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [26]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [27]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [28]:
np.linspace(1,20,40).shape

(40,)

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((5,2,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [35]:
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [36]:
np.random.rand(2,3) ## uniform distribution

array([[0.5661208 , 0.86697591, 0.65623195],
       [0.47742316, 0.68975622, 0.24015487]])

In [37]:
np.random.randn(2,3) ## normal distribution -> mean = 0, std dev = 1

array([[ 1.1831799 ,  0.62093009,  0.80321554],
       [-1.4519918 ,  0.28104991,  0.33000447]])

In [42]:
np.random.randint(1,100)

66

In [43]:
np.random.randint(1,100,10) # 10 random integers between 1 to 100

array([55, 39, 85, 64, 30, 11, 49,  8, 35,  4])

In [44]:
np.random.randint(1,100,(4,4))

array([[51, 61, 10, 68],
       [60, 70, 70,  7],
       [53, 63, 44, 75],
       [75, 40, 26,  1]])

In [46]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [49]:
arr[-1]

10

In [50]:
arr[-1:7]

array([], dtype=int64)

In [51]:
arr[-1:7:-1]

array([10,  9,  8])

In [52]:
arr[-1:3]

array([], dtype=int64)

In [53]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])