In [1]:
1+1

2

In [2]:
## numpy
import numpy as np

In [4]:
lst = [1,2,3,4]
arr=np.array(lst)
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr1.shape

(2, 3)

In [10]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr1.dtype

dtype('int64')

In [16]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.arange(1,10,2).shape

(5,)

In [20]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [23]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [26]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])