In [1]:
1+1

2

In [2]:
## numpy
import numpy as np

In [4]:
lst = [1,2,3,4]
arr=np.array(lst)
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr1.shape

(2, 3)

In [10]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr1.dtype

dtype('int64')

In [16]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.arange(1,10,2).shape

(5,)

In [20]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [23]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [26]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [27]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [28]:
np.linspace(1,20,40).shape

(40,)

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((5,2,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [35]:
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [36]:
np.random.rand(2,3) ## uniform distribution

array([[0.5661208 , 0.86697591, 0.65623195],
       [0.47742316, 0.68975622, 0.24015487]])

In [37]:
np.random.randn(2,3) ## normal distribution -> mean = 0, std dev = 1

array([[ 1.1831799 ,  0.62093009,  0.80321554],
       [-1.4519918 ,  0.28104991,  0.33000447]])

In [42]:
np.random.randint(1,100)

66

In [43]:
np.random.randint(1,100,10) # 10 random integers between 1 to 100

array([55, 39, 85, 64, 30, 11, 49,  8, 35,  4])

In [44]:
np.random.randint(1,100,(4,4))

array([[51, 61, 10, 68],
       [60, 70, 70,  7],
       [53, 63, 44, 75],
       [75, 40, 26,  1]])

In [46]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [49]:
arr[-1]

10

In [50]:
arr[-1:7]

array([], dtype=int64)

In [51]:
arr[-1:7:-1]

array([10,  9,  8])

In [52]:
arr[-1:3]

array([], dtype=int64)

In [53]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [55]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [59]:
arr1 = np.random.randint(2,100,20).reshape(5,4)
arr1

array([[33, 16, 31, 57],
       [18, 92, 72, 12],
       [95,  5, 50, 40],
       [38, 36, 80, 26],
       [ 2, 19, 30, 59]])

In [61]:
arr1[:3,:-1]


array([[33, 16, 31],
       [18, 92, 72],
       [95,  5, 50]])

In [62]:
arr1[3:,1:]

array([[36, 80, 26],
       [19, 30, 59]])

In [63]:
arr1

array([[33, 16, 31, 57],
       [18, 92, 72, 12],
       [95,  5, 50, 40],
       [38, 36, 80, 26],
       [ 2, 19, 30, 59]])

In [64]:
arr1[2:4,1:3]

array([[ 5, 50],
       [36, 80]])

In [67]:
arr1[2:4,:4:3]

array([[95, 40],
       [38, 26]])

In [68]:
## universal functions
arr1 = np.random.randint(1,100,(3,3))
arr2 = np.random.randint(20,100,(3,3))

In [69]:
arr1

array([[ 5, 94, 75],
       [51, 46,  7],
       [35, 86, 48]])

In [70]:
arr2

array([[29, 54, 44],
       [22, 20, 58],
       [77, 82, 39]])

In [71]:
arr1 * arr2

array([[ 145, 5076, 3300],
       [1122,  920,  406],
       [2695, 7052, 1872]])

In [72]:
arr1+arr2

array([[ 34, 148, 119],
       [ 73,  66,  65],
       [112, 168,  87]])

In [73]:
arr1/arr2

array([[0.17241379, 1.74074074, 1.70454545],
       [2.31818182, 2.3       , 0.12068966],
       [0.45454545, 1.04878049, 1.23076923]])

In [74]:
np.sqrt(arr1)

array([[2.23606798, 9.69535971, 8.66025404],
       [7.14142843, 6.78232998, 2.64575131],
       [5.91607978, 9.2736185 , 6.92820323]])

In [75]:
np.exp(arr2)

array([[3.93133430e+12, 2.83075330e+23, 1.28516001e+19],
       [3.58491285e+09, 4.85165195e+08, 1.54553894e+25],
       [2.75851345e+33, 4.09399696e+35, 8.65934004e+16]])

In [76]:
np.log10(arr1)

array([[0.69897   , 1.97312785, 1.87506126],
       [1.70757018, 1.66275783, 0.84509804],
       [1.54406804, 1.93449845, 1.68124124]])

In [77]:
arr1 = np.arange(1,10)

In [78]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr1[2:] = 1000

In [82]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])