In [2]:
import pandas as pd
import numpy as np

In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
# create a dataframe

In [6]:
pd.DataFrame(data=np.arange(0,20).reshape(5,4),columns=['a','b','c','d'])

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [8]:
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['a','b','c','d'])
df

a   b   c   d
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.head()

a   b   c   d
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [11]:
df.head(2)

a  b  c  d
row1  0  1  2  3
row2  4  5  6  7

In [12]:
df.tail(2)

a   b   c   d
row4  12  13  14  15
row5  16  17  18  19

In [13]:
df.describe()

a          b          c          d
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [15]:
df[['a','b','c']]

a   b   c
row1   0   1   2
row2   4   5   6
row3   8   9  10
row4  12  13  14
row5  16  17  18

In [19]:
df.loc[['row1','row3']]

a  b   c   d
row1  0  1   2   3
row3  8  9  10  11

In [25]:
df.iloc[[0,-1]]

a   b   c   d
row1   0   1   2   3
row5  16  17  18  19

In [26]:
df.iloc[1:4,:]

a   b   c   d
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15

In [27]:
df

a   b   c   d
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [30]:
df.iloc[2:4,1:3]

b   c
row3   9  10
row4  13  14

In [31]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [32]:
np.nan

nan

In [59]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=['row1','row2'],columns=['col1','col2','col3'])

In [34]:
df

col1  col2  col3
row1     1   NaN     2
row2     1   3.0     4

In [60]:
df[df.isnull()]

col1  col2  col3
row1   NaN   NaN   NaN
row2   NaN   NaN   NaN

In [35]:
df.isnull()

col1   col2   col3
row1  False   True  False
row2  False  False  False

In [36]:
df.isnull().sum()

col1    0
col2    1
col3    0
dtype: int64

In [37]:
df.dtypes

col1      int64
col2    float64
col3      int64
dtype: object

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    2 non-null      int64  
 1   col2    1 non-null      float64
 2   col3    2 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 64.0+ bytes


In [41]:
df.head()

col1  col2  col3
row1     1   NaN     2
row2     1   3.0     4

In [44]:
# value counts only gets applied to series
df['col1'].value_counts()

1    2
Name: col1, dtype: int64

In [45]:
df['col1'].unique()

array([1])

In [46]:
df['col1'].nunique()

1

In [47]:
df = pd.DataFrame({'A':[1,2,3],'B':[1,1,1]})

In [48]:
df

A  B
0  1  1
1  2  1
2  3  1

In [49]:
df['A'].unique()

array([1, 2, 3])

In [50]:
df['B'].unique()

array([1])

In [51]:
df['A'].nunique()

3

In [53]:
df.nunique(axis=0)

A    3
B    1
dtype: int64

In [72]:
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['a','b','c','d'])
df

a   b   c   d
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [55]:
df['b']>5

row1    False
row2    False
row3     True
row4     True
row5     True
Name: b, dtype: bool

In [56]:
df[df['b']>5]

a   b   c   d
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [58]:
df

a   b   c   d
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [66]:
df1=df.to_csv('test1.csv')
df1

In [63]:
df

a   b   c   d
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [75]:
df2 = df.to_csv('test2.csv',index=False)
df2

In [74]:
df2

In [76]:
df.to_excel('test3.xlsx')

In [77]:
pd.read_excel('test3.xlsx')

Unnamed: 0   a   b   c   d
0       row1   0   1   2   3
1       row2   4   5   6   7
2       row3   8   9  10  11
3       row4  12  13  14  15
4       row5  16  17  18  19

In [78]:
df.to_excel('test4.xlsx',index=False)

In [79]:
pd.read_excel('test4.xlsx')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [80]:
pd.read_csv("https://download.bls.gov/pub/time.series/cu/cu.item",sep='\t')

HTTPError: HTTP Error 403: Forbidden

In [81]:
data = '{"employee_name":"Deepjyoti","email":"deepjyotibhattacharjee217@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [82]:
data

'{"employee_name":"Deepjyoti","email":"deepjyotibhattacharjee217@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [85]:
df = pd.read_json(data)
df

employee_name                                email  \
0     Deepjyoti  deepjyotibhattacharjee217@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'Developer'}

In [84]:
data

'{"employee_name":"Deepjyoti","email":"deepjyotibhattacharjee217@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [86]:
df

employee_name                                email  \
0     Deepjyoti  deepjyotibhattacharjee217@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'Developer'}

In [89]:
df['title'] = dict(df['job_profile'])[0]['title']
df['role'] = dict(df['job_profile'])[0]['role']

In [90]:
df

employee_name                                email  \
0     Deepjyoti  deepjyotibhattacharjee217@gmail.com   

                                   job_profile      title       role  
0  {'title': 'Team Lead', 'role': 'Developer'}  Team Lead  Developer

In [91]:
df

employee_name                                email  \
0     Deepjyoti  deepjyotibhattacharjee217@gmail.com   

                                   job_profile      title       role  
0  {'title': 'Team Lead', 'role': 'Developer'}  Team Lead  Developer

In [92]:
pd.read_json(data,orient='records')

employee_name                                email  \
0     Deepjyoti  deepjyotibhattacharjee217@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'Developer'}

In [93]:
pd.read_json(data,orient='index')

0
employee_name                                      Deepjyoti
email                    deepjyotibhattacharjee217@gmail.com
job_profile    [{'title': 'Team Lead', 'role': 'Developer'}]

In [98]:
pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]